platform: linux

image_resource:
  type: docker-image
  source:
    repository: pierrevincent/gradle-java8
    tag: latest

inputs:
  - name: git-repo
  - name: version

outputs:
  - name: artifact-dir

run:
  path: sh
  args:
  - -c
  - |
    cd git-repo
    gradle check
    gradle assemble -PVersion=`cat version/number`
    find build/libs -type f -name "*.jar" -exec sh -c 'mkdir `basename "$0" .jar`; cp $0 `basename "$0" .jar`/`basename "$0"`' '{}' \;

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false