platform: linux

image_resource:
  type: docker-image
  source:
    repository: pierrevincent/gradle-java8
    tag: latest

inputs:
  - name: git-repo

run:
  path: sh
  args:
  - -c
  - gradle --build-file git-repo/build.gradle check

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false