platform: linux

image_resource:
  type: docker-image
  source:
    repository: pstauffer/curl
    tag: "latest"

inputs:
  - name: release-candidate

outputs:
  - name: final-dir

run:
  path: sh
  args:
  - -c
  - cp release-candidate/*.jar final-dir